/* Formatted on 02/09/2012 14:02:00 (QP5 v5.139.911.3011) */
--DROP PUBLIC SYNONYM OAUTH;
DROP USER AWS_SES CASCADE;
CREATE USER AWS_SES IDENTIFIED BY HoyllegaeliPhone5;
GRANT CONNECT, RESOURCE/*, CREATE VIEW, CREATE LIBRARY*/ TO AWS_SES;
GRANT EXECUTE ON DBMS_CRYPTO TO AWS_SES;
GRANT EXECUTE ON UTL_HTTP TO AWS_SES;