/* Formatted on 04/12/2012 10:59:24 (QP5 v5.163.1008.3004) */
DROP MATERIALIZED VIEW MSTR_DET_URGENCIAS_DEAYER;
CREATE MATERIALIZED VIEW MSTR_DET_URGENCIAS_DEAYER --(AU_USUARIO,USU_IDENTIFICADOR,USU_BDU_NUSA,AU_OPERADOR,AU_FECHA,AU_COD_PROCEDENCIA_URG,AU_COD_TIPO_PROCESO_URG,AU_EPISODIO,AU_FECHASALIDA,AU_FINANCIACION,EU_FHCREACION,EU_PRIORIDAD,EU_INFORMEALTA,EU_COD_CAUSA_ALTA_URG,EU_OPERADOR_FIRMA_ALTA,EU_FHALTA,EU_LUGAR_COD,EU_LUGAR_TXT,EUE_IDENTIFICADOR,UBICACION,IND_OBSERVACION,IND_EVOLUCION)
AS 
SELECT AU_USUARIO,
       USU_IDENTIFICADOR,
       USU_BDU_NUSA,
       AU_OPERADOR,
       AU_FECHA,
       AU_COD_PROCEDENCIA_URG,
       AU_COD_TIPO_PROCESO_URG,
       AU_EPISODIO,
       AU_FECHASALIDA,
       AU_FINANCIACION,
       EU_FHCREACION,
       EU_PRIORIDAD,
       EU_INFORMEALTA,
       EU_COD_CAUSA_ALTA_URG,
       EU_OPERADOR_FIRMA_ALTA,
       EU_FHALTA,
       EU_LUGAR_COD,
       EU_LUGAR_TXT,
       MAX_ESTADO.EUE_IDENTIFICADOR,
       EUE_UBICACION UBICACION,
       NVL (IND_OBSERVACION, 0) IND_OBSERVACION,
       NVL (IND_EVOLUCION, 0) IND_EVOLUCION
  --       ,
  --       (SELECT COUNT (EUE_IDENTIFICADOR)
  --          FROM CAE_OWN.ESTADOS_EPISODIO_URG EST1
  --         WHERE EUE_EPISODIO = AU_EPISODIO AND EST1.EUE_ESTADO = 10)
  --          IND_OBSERVACION,
  --       (SELECT COUNT (EUE_IDENTIFICADOR)
  --          FROM CAE_OWN.ESTADOS_EPISODIO_URG EST2
  --         WHERE EUE_EPISODIO = AU_EPISODIO AND EST2.EUE_ESTADO = 8)
  --          IND_EVOLUCION
  --       UBI1.UBI_NOMBRE SECCION,
  --       UBI0.UBI_NOMBRE AREA
  FROM CAE_OWN.ADMISION
       JOIN CAE_OWN.EPISODIO_URGENCIAS
          ON (AU_EPISODIO = EU_IDENTIFICADOR)
       JOIN (  SELECT EUE_EPISODIO, MAX (EUE_IDENTIFICADOR) EUE_IDENTIFICADOR
                 FROM CAE_OWN.ESTADOS_EPISODIO_URG
             GROUP BY EUE_EPISODIO) MAX_ESTADO
          ON (AU_EPISODIO = MAX_ESTADO.EUE_EPISODIO)
       JOIN CAE_OWN.ESTADOS_EPISODIO_URG ESTADOS
          ON (MAX_ESTADO.EUE_IDENTIFICADOR = ESTADOS.EUE_IDENTIFICADOR)
       /*       JOIN CAE_OWN.UBICACIONES_URGENCIAS UBI2
                 ON (ESTADOS.EUE_UBICACION = UBI2.UBI_IDENTIFICADOR)
              JOIN CAE_OWN.UBICACIONES_URGENCIAS UBI1
                 ON (UBI2.UBI_PADRE = UBI1.UBI_IDENTIFICADOR)
              LEFT JOIN CAE_OWN.UBICACIONES_URGENCIAS UBI0
                 ON (UBI1.UBI_PADRE = UBI0.UBI_IDENTIFICADOR)*/
       JOIN CAE_OWN.USUARIO
          ON (AU_USUARIO = USU_ID)
       LEFT JOIN (  SELECT EUE_EPISODIO, COUNT (EUE_IDENTIFICADOR) IND_OBSERVACION
                      FROM CAE_OWN.ESTADOS_EPISODIO_URG EST1
                      LEFT JOIN REP_PRO_EST.UBICACIONES UBI2
                    ON (EUE_UBICACION = UBI_CODIGO)
                     WHERE UBI2.UBI_NOMBRE LIKE 'Observación%' 
                     --EST1.EUE_ESTADO = 10
                  GROUP BY EUE_EPISODIO) EST_OBSERVACION
          ON (EST_OBSERVACION.EUE_EPISODIO = AU_EPISODIO)
       LEFT JOIN (SELECT EUE_EPISODIO, COUNT (EUE_IDENTIFICADOR) IND_EVOLUCION
                      FROM CAE_OWN.ESTADOS_EPISODIO_URG EST1
                      LEFT JOIN REP_PRO_EST.UBICACIONES UBI2
                    ON (EUE_UBICACION = UBI_CODIGO)
                     WHERE 
                     UBI2.UBI_NOMBRE LIKE 'Evolución%'
                     --EST1.EUE_ESTADO = 8
                  GROUP BY EUE_EPISODIO       ) EST_EVOLUCION
          ON (EST_EVOLUCION.EUE_EPISODIO = AU_EPISODIO)
 WHERE TRUNC (AU_FECHA) = TRUNC (SYSDATE) - 1;

--COMMENT ON MATERIALIZED VIEW MSTR_DET_URGENCIAS_DEAYER IS 'snapshot table for snapshot HIS_RND.MSTR_DET_URGENCIAS_DEAYER';

CREATE UNIQUE INDEX MSTR_DET_URGENCIAS_DEAYER_PK
   ON MSTR_DET_URGENCIAS_DEAYER (AU_EPISODIO)
   LOGGING
   NOPARALLEL;