CREATE VIEW MSTR_DET_TRASLADOS_URGENCIAS
AS
/* Formatted on 03/12/2012 9:48:32 (QP5 v5.163.1008.3004) */
  SELECT EUE_ACTIVO,
         EUE_CENTROENTRADA,
         EUE_EPISODIO,
         EST_NOMBRE,
         EUE_FHENTRADA,
         EUE_FHSALIDA,
         EUE_IDENTIFICADOR,
         --EUE_MOVILIDAD,
         --EUE_OPERENTRADA,
         EUE_UBICACION,
         NVL (URG.UBI_NOMBRE, EST.UBI_NOMBRE) DONDE
    FROM CAE_OWN.ESTADOS_EPISODIO_URG
         JOIN ESTADOS_URGENCIAS
            ON (EST_IDENTIFICADOR = EUE_ESTADO)
         LEFT JOIN CAE_OWN.UBICACIONES_AREAS URG
            ON (UBI_IDENTIFICADOR = EUE_UBICACION)
         LEFT JOIN REP_PRO_EST.UBICACIONES EST
            ON (UBI_CODIGO = EUE_UBICACION)
   --WHERE EUE_EPISODIO = 854147
--ORDER BY EUE_FHENTRADA