/* Formatted on 02/09/2012 14:02:00 (QP5 v5.139.911.3011) */
--DROP PUBLIC SYNONYM OAUTH;
DROP USER MSTR CASCADE;
CREATE USER MSTR IDENTIFIED BY KateMiddletonentopless;
GRANT CONNECT, RESOURCE/*, CREATE VIEW, CREATE LIBRARY*/ TO MSTR;
--GRANT EXECUTE ON DBMS_CRYPTO TO MSTR;
GRANT EXECUTE ON UTL_HTTP TO MSTR;