/* Formatted on 20/01/2014 12:33:01 (QP5 v5.163.1008.3004) PANDAS Copyright (c) 2013 -Davide Moraschi (davidem@eurostrategy.net)
Todos los derechos reservados. Prohibida su reproducción Total o Parcial. */
SELECT ORG_PLATAFORMA.CODIGO CODIGO_PLATAFORMA
			,ORG_PLATAFORMA.DESCRIPCION PLATAFORMA
			,ORG_ORGANOGESTOR.CODIGO CODIGO_ORGANO_GESTOR
			,ORG_ORGANOGESTOR.DESCRIPCION ORGANO_GESTOR
			,ORG_CENTROCONSUMO.CODIGO CODIGO_CENTRO_CONSUMO
			,ORG_CENTROCONSUMO.NOMBRE CENTRO_CONSUMO
			,PORCENTAJE
			,ORG_SERVICIOCC.ESTADO
			,'SERVICIO' TIPO_UNIDAD_RESPONSABLE
			,ORG_SERVICIO.CODIGO CODIGO_ENTIDAD_RESPONSABLE
			,ORG_SERVICIO.DESCRIPCION ENTIDAD_RESPONSABLE
	FROM REP_PRO_SIGLO.ORG_SERVICIOCC@SYG
			 JOIN REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG
				 ON (ORG_SERVICIOCC.CENTROCONSUMO = ORG_CENTROCONSUMO.ID)
			 JOIN REP_PRO_SIGLO.ORG_SERVICIO@SYG
				 ON (ORG_SERVICIOCC.SERVICIO = ORG_SERVICIO.ID)
			 JOIN REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
				 ON (ORG_CENTROCONSUMO.ORGANICA = ORG_ORGANOGESTOR.ID)
			 LEFT JOIN REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG ORG_PLATAFORMA
				 ON (ORG_ORGANOGESTOR.PLATAFORMA = ORG_PLATAFORMA.ID)
UNION ALL
SELECT ORG_PLATAFORMA.CODIGO CODIGO_PLATAFORMA
			,ORG_PLATAFORMA.DESCRIPCION PLATAFORMA
			,ORG_ORGANOGESTOR.CODIGO CODIGO_ORGANO_GESTOR
			,ORG_ORGANOGESTOR.DESCRIPCION ORGANO_GESTOR
			,ORG_CENTROCONSUMO.CODIGO CODIGO_CENTRO_CONSUMO
			,ORG_CENTROCONSUMO.NOMBRE CENTRO_CONSUMO
			,PORCENTAJE
			,ORG_UNIDADGESTIONCLINICACC.ESTADO
			,'UGC' TIPO_UNIDAD_RESPONSABLE
			,ORG_UNIDADGESTIONCLINICA.CODIGO CODIGO_ENTIDAD_RESPONSABLE
			,ORG_UNIDADGESTIONCLINICA.DESCRIPCION ENTIDAD_RESPONSABLE
	FROM REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICACC@SYG
			 JOIN REP_PRO_SIGLO.ORG_CENTROCONSUMO@SYG
				 ON (ORG_UNIDADGESTIONCLINICACC.CENTROCONSUMO = ORG_CENTROCONSUMO.ID)
			 JOIN REP_PRO_SIGLO.ORG_UNIDADGESTIONCLINICA@SYG
				 ON (ORG_UNIDADGESTIONCLINICACC.UNIDADGESTIONCLINICA = ORG_UNIDADGESTIONCLINICA.ID)
			 JOIN REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG
				 ON (ORG_CENTROCONSUMO.ORGANICA = ORG_ORGANOGESTOR.ID)
			 LEFT JOIN REP_PRO_SIGLO.ORG_ORGANOGESTOR@SYG ORG_PLATAFORMA
				 ON (ORG_ORGANOGESTOR.PLATAFORMA = ORG_PLATAFORMA.ID)
ORDER BY PLATAFORMA, ORGANO_GESTOR, CENTRO_CONSUMO